
# Site settings


# NB! Set your site's url, otherwise stuff will break :)

url: "https://jmquintana79.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /personal-jekyll-theme
baseurl: ""


# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Juan Quintana"
title: "{ Juan Quintana }"
description: "Blog and website of Juan Quintana, blogging mainly for tech. Opinions expressed are mine."
keywords: "dataming, python, modelling, development, websites"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/profile-juan.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 10

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: True
vkontakte-share: False

disqus-shortname: "jmquintana"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/logo-japan.png"
    date: "MAY 2015 - Currently"
    description: "Chief engineer in Japan Meteorological Corporation <small><i>Osaka, Japan</i></small>"
  - image: "/img/timeline/logo-ereda.png"
    date: "OCT 2012 - APR 2015"
    description: "Meteorological Technician & Senior Developer <br><a href='http://www.ereda.com/en/' target=\'_blank\'>EREDA, Renewable Energy Solutions</a> <br>C++, Python, R and Matlab, Data Analysis, Dynamical Forecast, Django Web Application <br><small><i>Madrid, Spain</i></small>"
  - image: "/img/timeline/logo-fic.jpg"
    date: "MAY 2010 - AUG 2012"
    description: "Meteorological Technician & Software Developer <br><a href='http://www.ficlima.org/' target=\'_blank\'>Foundation for Research of Climate Change (FIC)</a> <br>Fortran and R, Seasonal Forecast, Statistical Downscaling <br><small><i>Madrid, Spain</i></small>"
  - image: "/img/timeline/logo-aemet.png"
    date: "JAN 2010 - APR 2010"
    description: "Aeronautic Meteorological Observer <br><a href='http://www.aemet.es/en/portada' target=\'_blank\'>Meteorological Agency</a> <br><small><i>Malaga, Spain</i></small>"
  - image: "/img/timeline/logo-aemet.png"
    date: "MAY 2009 - JUN 2009"
    description: "Aeronautic Meteorological Observer Course <br><a href='http://www.aemet.es/en/portada' target=\'_blank\'>Meteorological Agency</a> <br><small><i>Madrid, Spain</i></small>"
  - image: "/img/timeline/logo-uned.jpg"
    date: "JAN 2009 - DEC 2009"
    description: "College Course <br>Satellite Remote Sensing <br><a href='http://portal.uned.es/portal/page?_pageid=93,24305391&_dad=portal&_schema=PORTAL' target=\'_blank\'>Spanish Distance Learning College</a>"
  - image: "/img/timeline/logo-aemet.png"
    date: "NOV 2007 - DEC 2009"
    description: "Fellow Graduate <br><a href='http://www.aemet.es/en/portada' target=\'_blank\'>Meteorological Agency</a> <br>Fortran, Seasonal Forecast, Dynamical Downscaling, Project with <a href='http://www.ecmwf.int/' target=\'_blank\'>ECMWF</a> <br><small><i>Madrid, Spain</i></small>"
  - image: "/img/timeline/logo-coritel.jpeg"
    date: "NOV 2006 - OCT 2007"
    description: "Junior Programmer <br><a href='https://www.accenture.com/' target=\'_blank\'>Coritel SA (Accenture)</a> <br><a href='http://www-03.ibm.com/software/products/en/ibmnotes' target=\'_blank\'>Lotus Notes</a> <br><small><i>Madrid, Spain</i></small>"
  - image: "/img/timeline/logo-coritel.jpeg"
    date: "SEP 2006 - OCT 2006"
    description: "Training Course <br><a href='https://www.accenture.com/' target=\'_blank\'>Coritel SA (Accenture)</a> <br><small><i>Madrid, Spain</i></small>"
  - image: "/img/timeline/logo-cplusplus.png"
    date: "2005"
    description: 'Course <br>"Programming languages" <br>C, C++ and Visual C++ <br><small><i>Guadalajara, Spain</i></small>'
  - image: "/img/timeline/logo-uam.jpg"
    date: "SEP 1999 - DEC 2004"
    description: "Degree in Physics <br><a href='http://www.uam.es/ss/Satellite/Ciencias/en/1242655567919/contenidoFinal/Fisica.htm' target=\'_blank\'>University of Madrid</a> <br><small><i>Madrid, Spain</i></small>"

# First image of the Timeline

timeline-img: "/img/timeline/logo_first-sleeping.jpg"

###########
# Contact #
###########

email: "juan.armaguedon@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://jp.linkedin.com/in/juan-quintana-ab884428"
  - title: "github"
    url: "https://github.com/jmquintana79"
  - title: "twitter"
    url: "https://twitter.com/jmquintana79"
  - title: "facebook"
    url: "http://facebook.com/juan.armagedon"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/dont_like.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins: #gems: # it was deprecated
  - jekyll-paginate
  - jemoji
#  - jekyll-gist # For new version Jekyll 3.0 in Github is neccesary but in local give a crash
